const dataknowledge  = [
  {
    red: "CULTURA",
    areas: [
      "PRODUCCIÓN AUDIOVISUAL",
      "MÚSICA",
      "MÚSICA PRODUCCIÓN AUDIO DIGITAL",
      "ARTES ESCÉNICAS - DANZA",
      "ARTES ESCÉNICAS - TEATRO",
    ],
  },
  {
    red: "ARTESANIAS",
    areas: [
      "CERÁMICA",
      "JOYERIA",
      "MADERABLES Y NO MADERABLES",
      "TEXTIL ARTESANAL",
    ],
  },
  {
    red: "ARTES GRÁFICAS",
    areas: [
      "DISEÑO GRÁFICO",
      "ENCUADERNACIÓN DE DOCUMENTOS IMPRESOS Y ACABADOS ESPECIALES",
      "PREPRENSA",
      "PRODUCCIÓN GRÁFICA",
    ],
  },
  {
    red: "GESTIÓN ADMINISTRATIVA Y FINANCIERA",
    areas: [
      "CONTABILIDAD",
      "FINANZAS",
      "GESTIÓN ADMINISTRATIVA",
      "TALENTO HUMANO",
      "GESTIÓN DOCUMENTAL",
      "BIBLIOTECAS",
      "SERVICIOS FINANCIEROS",
    ],
  },
  {
    red: "COMERCIO Y VENTAS",
    areas: [
      "CONTACT CENTER Y B.P.O",
      "NEGOCIACIÓN INTERNACIONAL",
      "GESTIÓN DE MERCADOS",
      "VENTAS",
    ],
  },
  {
    red: "AMBIENTAL",
    areas: [
      "GESTIÓN AMBIENTAL SECTORIAL Y URBANA",
      "AGROECOLOGÍA",
      "BIODIVERSIDAD",
      "FORESTAL",
      "GESTIÓN DEL RECURSO HÍDRICO",
    ],
  },
  {
    red: "BIOTECNOLOGÍA",
    areas: ["BIOTECNOLOGÍA INDUSTRIAL", "BIOTECNOLOGÍA VEGETAL"],
  },
  {
    red: "MECÁNICA INDUSTRIAL",
    areas: [
      "DISEÑO MECÁNICO",
      "MANTENIMIENTO MECÁNICO INDUSTRIAL",
      "MECANIZADO",
      "METROLOGÍA",
      "SOLDADURA",
    ],
  },
  {
    red: "ENERGÍA ELÉCTRICA",
    areas: [
      "GENERACIÓN DE LA ENERGÍA ELÉCTRICA",
      "TRANSMISIÓN DE LA ENERGÍA ELÉCTRICA",
      "DISTRIBUCIÓN DE LA ENERGÍA ELÉCTRICA",
      "USO FINAL DE LA ENERGÍA ELÉCTRICA",
    ],
  },
  {
    red: "ELECTRÓNICA Y AUTOMATIZACIÓN",
    areas: [
      "AUTOMATIZACIÓN INDUSTRIAL",
      "MANTENIMIENTO DE EQUIPO BIOMÉDICO",
      "ELECTRÓNICA",
      "INSTRUMENTACIÓN Y CONTROL DE PROCESOS",
      "MECATRÓNICA",
      "REFRIGERACIÓN, VENTILACIÓN Y CLIMATIZACIÓN (RVC)",
    ],
  },
  {
    red: "TELECOMUNICACIONES",
    areas: [
      "ELECTRICIDAD Y ELECTRÓNICA",
      "REDES CABLEADAS PARA TELECOMUNICACIONES",
      "CONVERGENCIA DE REDES Y SERVICIOS",
      "SISTEMA DE TELECOMUNICACIONES",
      "ADMINISTRACIÓN DE PROYECTOS",
    ],
  },
  {
    red: "QUÍMICA APLICADA",
    areas: ["ANÁLISIS QUÍMICO", "PROCESOS QUÍMICOS INDUSTRIALES"],
  },
  {
    red: "INFORMÁTICA, DISEÑO Y DESARROLLO DE SOFTWARE",
    areas: ["INFRAESTRUCTURA", "CONTENIDOS DIGITALES", "SOFTWARE"],
  },
  {
    red: "AUTOMOTOR",
    areas: [
      "MANTENIMIENTO ELECTROMECÁNICO DE EQUIPO PESADO",
      "MECATRÓNICA AUTOMOTRIZ",
      "MOTOCICLETAS",
    ],
  },
  {
    red: "AEROESPACIAL",
    areas: [
      "MANTENIMIENTO EN LÍNEA DE HELICÓPTEROS (TLH)",
      "MANTENIMIENTO ESPECIALIZADO EN SISTEMAS ELÉCTRICOS, ELECTRÓNICOS E INSTRUMENTOS DE AERONAVES (TEEI)",
      "MANTENIMIENTO EN LÍNEA DE AVIONES (TLA)",
    ],
  },
  {
    red: "TEXTIL, CONFECCIÓN, DISEÑO Y MODA",
    areas: [
      "GESTIÓN DE LA PRODUCCIÓN TEXTIL",
      "CONFECCIÓN INDUSTRIAL",
      "DISEÑO",
      "HILANDERÍA",
      "MANTENIMIENTO MAQUINARIA DE CONFECCIÓN",
      "NO TEJIDOS",
      "PATRONAJE",
      "TEJIDO DE PUNTO",
      "TEJIDO PLANO",
      "TINTORERÍA Y ACABADOS",
      "TRAZO Y CORTE EN CONFECCIÓN INDUSTRIAL",
    ],
  },
  {
    red: "CUERO CALZADO Y MARROQUINERÍA",
    areas: [
      "FABRICACIÓN DE CALZADO",
      "DISEÑO",
      "FABRICACIÓN DE MARROQUINERÍA",
      "GESTIÓN DE LA FABRICACIÓN EN CALZADO Y MARROQUINERÍA",
      "MODELAJE DE CALZADO",
      "MODELAJE DE MARROQUINERÍA",
      "CUERO",
    ],
  },
  {
    red: "MATERIALES PARA LA INDUSTRIA",
    areas: [
      "MADERA",
      "MATERIALES COMPUESTOS POLIMÉRICOS",
      "PLÁSTICOS",
      "DISEÑO DE PRODUCTOS",
    ],
  },
  {
    red: "MINERÍA",
    areas: ["MINERÍA"],
  },
  {
    red: "HIDROCARBUROS",
    areas: ["PRODUCCIÓN SUPERFICIE", "MANTENIMIENTO DE POZOS", "PERFORACIÓN"],
  },
  {
    red: "CONSTRUCCIÓN",
    areas: ["ARQUITECTURA Y DECORACIÓN", "CONSTRUCCIÓN", "HIDRÁULICA", "GAS"],
  },
  {
    red: "INFRAESTRUCTURA",
    areas: [
      "TOPOGRAFÍA",
      "OBRAS CIVILES",
      "OPERACIÓN DE MAQUINARIA PESADA PARA EXCAVACIÓN Y MOVIMIENTO DE TIERRA.",
    ],
  },
  {
    red: "AGRÍCOLA",
    areas: [
      "AGRICULTURA DE PRECISIÓN",
      "AGRICULTURA",
      "MECANIZACIÓN AGRÍCOLA",
      "RIEGO Y DRENAJES AGRÍCOLAS",
      "AGROINDUSTRIAL - CONTROL DE CALIDAD E INOCUIDAD",
      "PROCESAMIENTO DE ALIMENTOS – FRUTAS Y VERDURAS",
      "PROCESAMIENTO DE ALIMENTOS – CHOCOLATERÍA Y CONFITERÍA",
      "PROCESAMIENTO DE ALIMENTOS – PANADERIA Y REPOSTERIA",
      "PROCESAMIENTO DE ALIMENTOS – LÁCTEOS Y DERIVADOS",
      "PROCESAMIENTO DE ALIMENTOS – PESCADOS Y MARISCOS",
    ],
  },
  {
    red: "PECUARIA",
    areas: ["PRODUCCIÓN ESPECIES MAYORES", "PRODUCCIÓN ESPECIES MENORES"],
  },
  {
    red: "ACUÍCOLA Y DE PESCA",
    areas: ["ACUICULTURA", "PESCA"],
  },
  {
    red: "SALUD",
    areas: [
      "DISPOSITIVOS MÉDICOS - BIOMÉDICOS",
      "SERVICIOS FARMACÉUTICOS",
      "APOYO AL DIAGNOSTICO",
      "APOYO TERAPÉUTICO Y REHABILITACIÓN",
      "SALUD PÚBLICA",
    ],
  },
  {
    red: "HOTELERÍA Y TURISMO",
    areas: [
      "SERVICIOS DE ALOJAMIENTO",
      "SERVICIOS DE AGENCIAS DE VIAJES",
      "GUIANZA TURÍSTICA",
      "TURISMO",
      "EVENTOS",
      "BARISMO",
      "COCINA",
      "MESA Y BAR",
    ],
  },
  {
    red: "ACTIVIDAD FÍSICA, RECREACIÓN Y DEPORTE",
    areas: ["ACTIVIDAD FÍSICA", "DEPORTE", "GESTIÓN DEPORTIVA", "RECREACIÓN"],
  },
  {
    red: "TRANSPORTE",
    areas: [
      "TRANSPORTE TERRESTRE FÉRREO",
      "TRANSPORTE FLUVIAL",
      "TRANSPORTE MARÍTIMO",
      "TRANSPORTE TERRESTRE POR CARRETERA",
    ],
  },
  {
    red: "SERVICIOS PERSONALES",
    areas: ["BELLEZA"],
  },
  {
    red: "LOGÍSTICA Y GESTIÓN DE LA PRODUCCIÓN",
    areas: [
      "GESTIÓN LOGÍSTICA",
      "SISTEMA INTEGRADO DE GESTIÓN",
      "PRODUCCIÓN INDUSTRIAL",
      "SEGURIDAD Y SALUD EN EL TRABAJO",
    ],
  },
  {
    red: "INSTITUCIONAL DE PEDAGOGÍA",
    areas: [
      "CIENCIAS NATURALES",
      "COMUNICACIÓN",
      "CULTURA FÍSICA",
      "DERECHOS HUMANOS Y FUNDAMENTALES EN EL TRABAJO",
      "EDUMÁTICA EN LA FORMACIÓN PROFESIONAL",
      "EMPRENDIMIENTO",
      "ENFOQUE DIFERENCIAL",
      "EXTENSIÓN Y DESARROLLO RURAL Y COMUNITARIO",
      "IDIOMAS",
      "INTERACCIÓN CONSIGO MISMO, CON LOS DEMÁS, CON LA NATURALEZA Y CON LA TRASCENDENCIA",
      "MATEMÁTICAS",
      "PROTECCIÓN AMBIENTAL, SEGURIDAD Y SALUD EN EL TRABAJO",
      "COORDINACIÓN ACADÉMICA",
      "PEDAGOGÍA Y DIDÁCTICA PARA LA FORMACIÓN PROFESIONAL",
    ],
  },
];

export default dataknowledge;
