
<template>
  <div class="q-pa-md q-gutter-sm">
    <div id="calenderPrint">
      <FullCalendar
        id="calender"
        class="text-uppercase"
        :options="calendarOptions"
      >
        <template v-slot:eventContent="arg">
          <VMenu
            :autoHide="false"
            :delay="0"
            class="justify-center items-center customEvents"
          >
            <span>
              <b>{{ arg.timeText }}</b> <i>{{ arg.event.title }}</i></span
            >

            <template #popper>
              <div class="content-tooltip-event">
                <p>INSTRUCTOR: {{ arg.event.extendedProps.instructor }}</p>
                <p>AMBIENTE: {{ arg.event.extendedProps.environment }}</p>
                <p>PROGRAMA: {{ arg.event.extendedProps.program }}</p>
                <p>RESULTADO: {{ arg.event.extendedProps.outcome }}</p>
                <p>HORA INICIO: {{ arg.event.extendedProps.tstart }}</p>
                <p>HORA FIN: {{ arg.event.extendedProps.tend }}</p>
              </div>
            </template>
          </VMenu>
        </template>
      </FullCalendar>
    </div>
  </div>
</template>

<script setup>
import { ref, onBeforeMount, computed } from "vue";
import { useQuasar } from "quasar";

import FullCalendar from "@fullcalendar/vue3";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import esLocale from "@fullcalendar/core/locales/es";

const $q = useQuasar();

let calendarOptions = ref({
  plugins: [dayGridPlugin, timeGridPlugin, interactionPlugin],
  locale: esLocale,
  initialView: "dayGridMonth",
  selectable: true,
  initialDate: new Date(),
  fixedWeekCount: false,
  headerToolbar: {
    left: "",
    center: "title",
    right: "",
  },
  events: [
    {
      id: 1,
      idInstructor: "34535345345",
      fiche: "438543895943853948",
      program:
        "progrddd sdfsdifbihsdb ifsdbifhb siuhdbifb sifi bsdibf sbdhfjbihsdbfisdifbdshbfkjsd fsdbn",
      environment: "igbdgbhdfgbidfgd ndfing ndfkng knkdfgnkfdnkjgnkdf",
      outcome: "dfhgbhbfdgbdf gndfn gindkfgnd gdknfk lgndfk",
      competence: "dfijnidfgidfgdf gdfg dfg dfggdgdfgdfgdf",
      title: "38- instructor pepito perez",
      start: "2023-08-14",
      tstart: "14:00",
      tend: "16:00",
      type: 0,
      autogenerated: true,
    },
    {
      id: 2,
      idInstructor: "3453534534435435",
      fiche: "438543895943853948",
      program:
        "progrddd sdfsdifbihsdb ifsdbifhb siuhdbifb sifi bsdibf sbdhfjbihsdbfisdifbdshbfkjsd fsdbn",
      environment: "igbdgbhdfgbidfgd ndfing ndfkng knkdfgnkfdnkjgnkdf",
      outcome: "dfhgbhbfdgbdf gndfn gindkfgnd gdknfk lgndfk",
      competence: "dfijnidfgidfgdf gdfg dfg dfggdgdfgdfgdf",
      title: "38- instructor pepito perez",
      start: "2023-08-01",
      tstart: "14:00",
      tend: "16:00",
      type: 0,
      autogenerated: true,
    },
    {
      id: 3,
      idInstructor: "3453534534435435",
      fiche: "438543895943853948",
      program:
        "progrddd sdfsdifbihsdb ifsdbifhb siuhdbifb sifi bsdibf sbdhfjbihsdbfisdifbdshbfkjsd asduh bashiubihasbiu bdiasbi basidb uiabsuid biuasbdih bahsdbiusab iubsadhib asuibu asbih rogrddd sdfsdifbihsdb ifsdbifhb siuhdbifb sifi bsdibf sbdhfjbihsdbfisdifbdshbfkjsd asduh bashiubihasbiu bdiasbi basidb uiabsuid biuasbdih bahsdbiusab iubsadhib asuibu asbihdasbi ashdbasias fsdbn rogrddd sdfsdifbihsdb ifsdbifhb siuhdbifb sifi bsdibf sbdhfjbihsdbfisdifbdshbfkjsd asduh bashiubihasbiu bdiasbi basidb uiabsuid biuasbdih bahsdbiusab iubsadhib asuibu asbihdasbi ashdbasias fsdbndasbi ashdbasias fsdbn",
      environment:
        "igbd rogrddd sdfsdifbihsdb ifsdbifhb siuhdbifb sifi bsdibf sbdhfjbihsdbfisdifbdshbfkjsd asduh bashiubihasbiu bdiasbi basidb uiabsuid biuasbdih bahsdbiusab iubsadhib asuibu asbihdasbi ashdbasias fsdbn gbhdfgbidfgd ndfing adasjkdkas asjd kjaskb khalsbdkl askdbk asbkdb kasbkld bkasbdkl bkand bknasbdn bas ndfkng knkdfgnkfdnkjgnkdf",
      outcome: "dfhgbhbfdgbdf gndfn gindkfgnd gdknfk lgndfk",
      competence: "dfijnidfgidfgdf gdfg dfg dfggdgdfgdfgdf",
      title: "38- instructor pepito perez",
      start: "2023-08-01",
      tstart: "14:00",
      tend: "16:00",
      type: 0,
      autogenerated: true,
    },
  ],
});
</script>

<style >
</style>
