const municipiosSantander = [
  "Aguada",
  "Albania",
  "Almeida",
  "Amparo",
  "Aratoca",
  "Barbosa",
  "Barichara",
  "Barrancabermeja",
  "Betulia",
  "Bolívar",
  "Bucaramanga",
  "Cabrera",
  "California",
  "Capitanejo",
  "Carcasí",
  "Cepitá",
  "Cerrito",
  "Charalá",
  "Charta",
  "Chima",
  "Chipatá",
  "Cimitarra",
  "Concepción",
  "Confines",
  "Contratación",
  "Coromoro",
  "Curití",
  "El Carmen de Chucurí",
  "El Guacamayo",
  "El Peñón",
  "El Playón",
  "Encino",
  "Enciso",
  "Florián",
  "Floridablanca",
  "Galán",
  "Gambita",
  "Girón",
  "Guaca",
  "Guadalupe",
  "Guapotá",
  "Guavatá",
  "Güepsa",
  "Hato",
  "Jesús María",
  "Jordán",
  "La Belleza",
  "La Paz",
  "Landázuri",
  "Lebrija",
  "Los Santos",
  "Macaravita",
  "Málaga",
  "Matanza",
  "Mogotes",
  "Molagavita",
  "Ocamonte",
  "Oiba",
  "Onzaga",
  "Palmar",
  "Palmas del Socorro",
  "Páramo",
  "Piedecuesta",
  "Pinchote",
  "Puente Nacional",
  "Puerto Parra",
  "Puerto Wilches",
  "Rionegro",
  "Sabana de Torres",
  "San Andrés",
  "San Benito",
  "San Gil",
  "San Joaquín",
  "San José de Miranda",
  "San Miguel",
  "San Vicente de Chucurí",
  "Santa Bárbara",
  "Santa Helena del Opón",
  "Simacota",
  "Socorro",
  "Suaita",
  "Sucre",
  "Suratá",
  "Tona",
  "Valle de San José",
  "Vélez",
  "Vetas",
  "Villanueva",
  "Zapatoca",
];

const municipiosAntioquia = [
  "MEDELLIN",
  "ABEJORRAL",
  "ABRIAQUI",
  "ALEJANDRIA",
  "AMAGA",
  "AMALFI",
  "ANDES",
  "ANGELOPOLIS",
  "ANGOSTURA",
  "ANORI",
  "SANTAFE DE ANTIOQUIA",
  "ANZA",
  "APARTADO",
  "ARBOLETES",
  "ARGELIA",
  "ARMENIA",
  "BARBOSA",
  "BELMIRA",
  "BELLO",
  "BETANIA",
  "BETULIA",
  "CIUDAD BOLIVAR",
  "BRICEÑO",
  "BURITICA",
  "CACERES",
  "CAICEDO",
  "CALDAS",
  "CAMPAMENTO",
  "CAÑASGORDAS",
  "CARACOLI",
  "CARAMANTA",
  "CAREPA",
  "EL CARMEN DE VIBORAL",
  "CAROLINA",
  "CAUCASIA",
  "CHIGORODO",
  "CISNEROS",
  "COCORNA",
  "CONCEPCION",
  "CONCORDIA",
  "COPACABANA",
  "DABEIBA",
  "DON MATIAS",
  "EBEJICO",
  "EL BAGRE",
  "ENTRERRIOS",
  "ENVIGADO",
  "FREDONIA",
  "FRONTINO",
  "GIRALDO",
  "GIRARDOTA",
  "GOMEZ PLATA",
  "GRANADA",
  "GUADALUPE",
  "GUARNE",
  "GUATAPE",
  "HELICONIA",
  "HISPANIA",
  "ITAGUI",
  "ITUANGO",
  "JARDIN",
  "JERICO",
  "LA CEJA",
  "LA ESTRELLA",
  "LA PINTADA",
  "LA UNION",
  "LIBORINA",
  "MACEO",
  "MARINILLA",
  "MONTEBELLO",
  "MURINDO",
  "MUTATA",
  "NARIÑO",
  "NECOCLI",
  "NECHI",
  "OLAYA",
  "PEÐOL",
  "PEQUE",
  "PUEBLORRICO",
  "PUERTO BERRIO",
  "PUERTO NARE",
  "PUERTO TRIUNFO",
  "REMEDIOS",
  "RETIRO",
  "RIONEGRO",
  "SABANALARGA",
  "SABANETA",
  "SALGAR",
  "SAN ANDRES DE CUERQUIA",
  "SAN CARLOS",
  "SAN FRANCISCO",
  "SAN JERONIMO",
  "SAN JOSE DE LA MONTAÑA",
  "SAN JUAN DE URABA",
  "SAN LUIS",
  "SAN PEDRO",
  "SAN PEDRO DE URABA",
  "SAN RAFAEL",
  "SAN ROQUE",
  "SAN VICENTE",
  "SANTA BARBARA",
  "SANTA ROSA DE OSOS",
  "SANTO DOMINGO",
  "EL SANTUARIO",
  "SEGOVIA",
  "SONSON",
  "SOPETRAN",
  "TAMESIS",
  "TARAZA",
  "TARSO",
  "TITIRIBI",
  "TOLEDO",
  "TURBO",
  "URAMITA",
  "URRAO",
  "VALDIVIA",
  "VALPARAISO",
  "VEGACHI",
  "VENECIA",
  "VIGIA DEL FUERTE",
  "YALI",
  "YARUMAL",
  "YOLOMBO",
  "YONDO",
  "ZARAGOZA",
];

const municipiosAtlantico = [
  "BARRANQUILLA",
  "BARANOA",
  "CAMPO DE LA CRUZ",
  "CANDELARIA",
  "GALAPA",
  "JUAN DE ACOSTA",
  "LURUACO",
  "MALAMBO",
  "MANATI",
  "PALMAR DE VARELA",
  "PIOJO",
  "POLONUEVO",
  "PONEDERA",
  "PUERTO COLOMBIA",
  "REPELON",
  "SABANAGRANDE",
  "SABANALARGA",
  "SANTA LUCIA",
  "SANTO TOMAS",
  "SOLEDAD",
  "SUAN",
  "TUBARA",
  "USIACURI",
];

const municipiosBogota = ["BOGOTA D.C."];


const municipiosBolivar = [
    "CARTAGENA",
    "ACHI",
    "ALTOS DEL ROSARIO",
    "ARENAL",
    "ARJONA",
    "ARROYOHONDO",
    "BARRANCO DE LOBA",
    "CALAMAR",
    "CANTAGALLO",
    "CICUCO",
    "CORDOBA",
    "CLEMENCIA",
    "EL CARMEN DE BOLIVAR",
    "EL GUAMO",
    "EL PEÑON",
    "HATILLO DE LOBA",
    "MAGANGUE",
    "MAHATES",
    "MARGARITA",
    "MARIA LA BAJA",
    "MONTECRISTO",
    "MOMPOS",
    "NOROSI",
    "MORALES",
    "PINILLOS",
    "REGIDOR",
    "RIO VIEJO",
    "SAN CRISTOBAL",
    "SAN ESTANISLAO",
    "SAN FERNANDO",
    "SAN JACINTO",
    "SAN JACINTO DEL CAUCA",
    "SAN JUAN NEPOMUCENO",
    "SAN MARTIN DE LOBA",
    "SAN PABLO",
    "SANTA CATALINA",
    "SANTA ROSA",
    "SANTA ROSA DEL SUR",
    "SIMITI",
    "SOPLAVIENTO",
    "TALAIGUA NUEVO",
    "TIQUISIO",
    "TURBACO",
    "TURBANA",
    "VILLANUEVA",
    "ZAMBRANO"
  ];
  
  const municipiosBoyaca = [
    "TUNJA",
    "ALMEIDA",
    "AQUITANIA",
    "ARCABUCO",
    "BELEN",
    "BERBEO",
    "BETEITIVA",
    "BOAVITA",
    "BOYACA",
    "BRICEÑO",
    "BUENAVISTA",
    "BUSBANZA",
    "CALDAS",
    "CAMPOHERMOSO",
    "CERINZA",
    "CHINAVITA",
    "CHIQUINQUIRA",
    "CHISCAS",
    "CHITA",
    "CHITARAQUE",
    "CHIVATA",
    "CIENEGA",
    "COMBITA",
    "COPER",
    "CORRALES",
    "COVARACHIA",
    "CUBARA",
    "CUCAITA",
    "CUITIVA",
    "CHIQUIZA",
    "CHIVOR",
    "DUITAMA",
    "EL COCUY",
    "EL ESPINO",
    "FIRAVITOBA",
    "FLORESTA",
    "GACHANTIVA",
    "GAMEZA",
    "GARAGOA",
    "GUACAMAYAS",
    "GUATEQUE",
    "GUAYATA",
    "GÜICÁN",
    "IZA",
    "JENESANO",
    "JERICÓ",
    "LABRANZAGRANDE",
    "LA CAPILLA",
    "LA VICTORIA",
    "LA UVITA",
    "VILLA DE LEYVA",
    "MACANAL",
    "MARIPI",
    "MIRAFLORES",
    "MONGUA",
    "MONGUI",
    "MONIQUIRÁ",
    "MOTAVITA",
    "MUZO",
    "NOBSA",
    "NUEVO COLÓN",
    "OICATÁ",
    "OTANCHE",
    "PACHAVITA",
    "PÁEZ",
    "PAIPA",
    "PAJARITO",
    "PANQUEBA",
    "PAUNA",
    "PAYA",
    "PAZ DE RÍO",
    "PESCA",
    "PISBA",
    "PUERTO BOYACÁ",
    "QUIPAMA",
    "RAMIRIQUÍ",
    "RAQUIRA",
    "RONDÓN",
    "SABOYÁ",
    "SÁCHICA",
    "SAMACÁ",
    "SAN EDUARDO",
    "SAN JOSÉ DE PARE",
    "SAN LUIS DE GACENO",
    "SAN MATEO",
    "SAN MIGUEL DE SEMA",
    "SAN PABLO DE BORBUR",
    "SANTANA",
    "SANTA MARÍA",
    "SANTA ROSA DE VITERBO",
    "SANTA SOFÍA",
    "SATIVANORTE",
    "SATIVASUR",
    "SIACHOQUE",
    "SOATÁ",
    "SOCOTÁ",
    "SOCHA",
    "SOGAMOSO",
    "SOMONDOCO",
    "SORA",
    "SOTAQUIRÁ",
    "SORACÁ",
    "SUSACÓN",
    "SUTAMARCHÁN",
    "SUTATENZA",
    "TASCO",
    "TENZA",
    "TIBANÁ",
    "TIBASOSA",
    "TINJACÁ",
    "TIPACOQUE",
    "TOCA",
    "TOGÜÍ",
    "TOPAGÁ",
    "TOTA",
    "TUNUNGUÁ",
    "TURMEQUÉ",
    "TUTA",
    "TUTAZÁ",
    "UMBITA",
    "VENTAQUEMADA",
    "VIRACACHÁ",
    "ZETAQUIRA"
  ];
  