import { formatDate12Hours } from "./dates.js"

function formatEventSchedule(schedule,event,index,color,autogenerated,title =null){
    return{
        id: index,
        code:schedule._id,
        fiche:schedule.fiche.number,
        idInstructor:schedule.instructor._id,
        instructor:schedule.instructor.name,
        title:title ? title : schedule.instructor.name,
        program:schedule.program.name,
        supporttext:schedule.supporttext,
        observation:schedule.observation,
        environment:schedule.environment.name,
        outcome:schedule.outcome.outcomes,
        competence:schedule.competence.name,
        start:event.toISOString().split("T")[0],
        tstart:formatDate12Hours(schedule.tstart),
        tend:formatDate12Hours(schedule.tend),
        backgroundColor:color.background,
        borderColor:color.background,
        textColor:color.colortext,
        type:0,
        autogenerated:autogenerated
    }
}

function formatEventOtherSchedule(schedule,event,index,color,autogenerated){
    return{
        id: index,
        code:schedule._id,
        idInstructor:schedule.instructor._id,
        typeactivity:schedule.typeactivity,
        additionalactivity:schedule.additionalactivity,
        justification:schedule.justification,
        title:schedule.instructor.name,
        start:event.toISOString().split("T")[0],
        tstart:formatDate12Hours(schedule.tstart),
        tend:formatDate12Hours(schedule.tend),
        backgroundColor:color.background,
        borderColor:color.background,
        textColor:color.colortext,
        type:1,
        autogenerated:autogenerated
    }
}



export {formatEventSchedule,formatEventOtherSchedule}